site_name: Yuvaraj Blog
site_description: A blog about technology, programming, and personal projects.
site_url: https://yuvarajk7.github.io/yblog
copyright: © 2025 Yuvaraj Blog

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.annotate
  font:
    text: Inter
    code: Fira Code

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: #2B3459
      accent: #008080

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: #2B3459
      accent: #008080
extra:
  social:
    - icon: material/rss
      link: yuvarss.xml

extra_css:
  - stylesheets/extra.css

# extra_javascript:
#   - javascripts/extra.js

plugins:
  - exclude:
      glob:
        - "docs/drafts/*"
  - search
  #- mermaid2
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
      remove_comments: true
      cache_safe: true
  - blog:
      blog_dir: .
      archive_date_format: MM/yyyy
      archive_url_date_format: MM/yyyy
      categories_allowed:
        - Technology
        - Programming
        - AI
  - tags:
      tags_file: tags.md
  - rss:
      feed_title: "Yuvaraj AI Blog"
      feed_description: "Yuvaraj article feeds"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      match_path: "^posts/(?!index\\.md$|tags\\.md$|glimages/|image-post\\.md$).+\\.md$"
      pretty_print: true
      rss_feed_enabled: true
      abstract_chars_count: 160
      categories:
        - categories
      comments_path: "#__comments"
      exclude_unreferenced: true
      feed_ttl: 1440
      length: 20
      feeds_filenames:
        rss_created: yuvarss.xml
        rss_updated: feed_rss_updated.xml

  - glightbox:
      touchNavigation: true
      loop: true
      effect: fade
      width: 80%
      height: auto
      zoomable: true
      draggable: true

 

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format